<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns="http://www.mulesoft.org/schema/mule/core" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:spring="http://www.springframework.org/schema/beans"
    xmlns:test="http://www.mulesoft.org/schema/mule/test"
    xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
        http://www.mulesoft.org/schema/mule/test http://www.mulesoft.org/schema/mule/test/current/mule-test.xsd
        http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.0.xsd">

    <description>
        reproduce error that crashes seda service when seda
        queue is full
    </description>

    <queued-asynchronous-processing-strategy
        name="max2ThreadSmallTimeout" maxThreads="2"
        poolExhaustedAction="WAIT" threadWaitTimeout="500" />

    <queued-asynchronous-processing-strategy
            name="smallQueue" maxQueueSize="1" maxThreads="1"
            poolExhaustedAction="RUN" threadWaitTimeout="20" />

    <flow name="limitedThreadsFlow" processingStrategy="max2ThreadSmallTimeout">
        <test:component waitTime="1000" />
        <test:queue name="out"/>
        <catch-exception-strategy>
            <test:queue name="exception"/>
        </catch-exception-strategy>
    </flow>

    <flow name="limitedQueueFlow" processingStrategy="smallQueue">
        <test:component waitTime="50" />
        <test:queue name="out"/>
        <catch-exception-strategy>
            <test:queue name="exception"/>
        </catch-exception-strategy>
    </flow>

</mule>
